# Contenido del bot: palabras curiosas, refranes y frases míticas

PALABRAS_CURIOSAS = [
    "Acendrado: Puro, sin mancha ni defecto",
    "Ademán: Movimiento o actitud del cuerpo o de alguna parte suya con que se manifiesta disposición, intención o sentimiento",
    "Albricias: Expresión de júbilo o alegría por una buena noticia",
    "Alipende: Se refiere a una persona pilla, traviesa o 'de una pieza'",
    "Arrebol: Color rojo, especialmente el de las nubes iluminadas por los rayos del sol o el del rostro",
    "Ataraxia: Imperturbabilidad, serenidad",
    "Aurora: Luz sonrosada que precede a la salida del sol",
    "Bálsamo: Consuelo, alivio para las penas del alma",
    "Balumba: Conjunto desordenado y excesivo de cosas",
    "Bonhomía: Afabilidad, sencillez y bondad en el carácter",
    "Cáfila: Conjunto numeroso de personas, animales o cosas",
    "Crepúsculo: Claridad que hay desde que raya el día hasta que sale el sol, y desde que se pone hasta que es de noche",
    "Denuedo: Brío, esfuerzo, valor, intrepidez",
    "Duende: Encanto misterioso e inexplicable de algo o alguien",
    "Efímero: Que dura muy poco tiempo, pasajero",
    "Elocuente: Que tiene la capacidad de expresarse con claridad y convicción",
    "Embeleco: Engaño, embuste con que se pretende alucinar a alguien",
    "Epifanía: Manifestación o aparición repentina de una idea o verdad",
    "Etéreo: Sutil, vago, vaporoso, tan delicado que parece no ser de este mundo",
    "Evanescente: Que se desvanece o esfuma como el vapor",
    "Fruslería: Cosa de poco valor o importancia",
    "Gazmoño: Que finge devoción, escrúpulos o modestia exagerada",
    "Hogaño: En este año, en la época actual",
    "Ignoto: Desconocido, no descubierto",
    "Indócil: que no tiene la cualidad de ser obediente",
    "Inefable: Que no puede explicar con palabras",
    "Jolgorio: Diversión bulliciosa, fiesta ruidosa",
    "Lacónico: Breve, conciso, que usa pocas palabras",
    "Limerencia: Estado mental involuntario de atracción romántica obsesiva",
    "Medroso: Que tiene miedo con facilidad, temeroso",
    "Melifluo: Dulce, suave, delicado y tierno en el trato o en la manera de hablar",
    "Mohíno: Triste, melancólico, disgustado",
    "Nefelibata: Persona soñadora que vive en las nubes",
    "Nimio: Insignificante, sin importancia",
    "Obnubilar: Ofuscar, nublar la razón o el entendimiento",
    "Onirico: Relativo a los sueños",
    "Orate: Persona que ha perdido el juicio, loco",
    "Pávido: Tímido, medroso, lleno de pavor",
    "Petricor: el olor de la lluvia al caer sobre tierra seca",
    "Procrastinar: posponer tareas constantemente",
    "Querencia: Tendencia del ser humano hacia su lugar de origen o preferido",
    "Quimera: Ilusión, fantasía que se cree posible pero no lo es",
    "Raudo: Rápido, veloz, precipitado",
    "Resiliencia: Capacidad de adaptarse positivamente a situaciones adversas",
    "Saudade: Nostalgia melancólica por algo o alguien ausente",
    "Sempiterno: Que durará siempre, eterno",
    "Serendipia: descubrimiento afortunado e inesperado",
    "Soliviantar: Inquietar, alterar el ánimo de alguien",
    "Sonámbulo: Que camina o realiza actividades mientras duerme",
    "Trasegar: Revolver, trastornar, cambiar de lugar",
    "Ubérrimo: Muy abundante y fértil",
    "Vesania: Locura, furia, demencia",
    "Zalamero: Que hace zalamerías, muy cariñoso con intención",
]

REFRANES = [
    "A buen entendedor, pocas palabras bastan",
    "A caballo regalado no le mires el dentado",
    "A falta de pan, buenas son tortas",
    "A otro perro con ese hueso",
    "A palabras necias, oídos sordos",
    "A quien madruga, Dios le ayuda",
    "Agua que no has de beber, déjala correr",
    "Al pan, pan y al vino, vino",
    "Año de nieves, año de bienes",
    "Aunque la mona se vista de seda, mona se queda",
    "Barriga llena, corazón contento",
    "Boda y mortaja, del cielo bajan",
    "Cada loco con su tema",
    "Cara bonita, poco dura",
    "Cría cuervos y te sacarán los ojos",
    "Cuando el río suena, agua lleva",
    "Cuando marzo mayea, mayo marcea",
    "De noche todos los gatos son pardos",
    "De tal palo, tal astilla",
    "Del dicho al hecho hay mucho trecho",
    "Desgracia compartida, menos sentida",
    "Dime con quién andas y te diré quién eres",
    "Dime qué posteas y te diré quién eres",
    "Donde las dan, las toman",
    "El hábito no hace al monje",
    "El ojo del amo engorda el caballo",
    "El que guarda, halla",
    "El que mucho abarca, poco aprieta",
    "El que tropieza dos veces con la misma piedra, merece que se le caiga encima",
    "El tiempo todo lo cura",
    "En boca cerrada no entran moscas",
    "En casa del herrero, cuchillo de palo",
    "Entre broma y broma, la verdad se asoma",
    "Gato escaldado del agua fría huye",
    "Genio y figura hasta la sepultura",
    "Golondrina que por San Blas ves, o se helará o hambre tendrá",
    "Hecha la ley, hecha la VPN",
    "Hierba mala nunca muere",
    "Hijo de tigre sale rayado",
    "La avaricia rompe el saco",
    "La cabra siempre tira al monte",
    "La curiosidad mató al gato",
    "La esperanza es lo último que se pierde",
    "La ocasión hace al ladrón",
    "La pereza anda tan despacio que la pobreza la alcanza",
    "Las apariencias engañan",
    "Lo barato sale caro",
    "Lo prometido es deuda",
    "Lo que no mata, engorda",
    "Los trapos sucios se lavan en casa",
    "Mal de muchos, consuelo de tontos",
    "Más sabe el diablo por viejo que por diablo",
    "Más vale maña que fuerza",
    "Más vale pájaro en mano que ciento volando",
    "Más vale prevenir que curar",
    "Más vale solo que mal acompañado",
    "Más vale tarde que nunca",
    "Más vale un backup a tiempo que cien disculpas después",
    "Muerto el perro, se acabó la rabia",
    "Nadie es profeta en su tierra",
    "No dejes para mañana lo que puedas hacer hoy",
    "No es lo mismo llamar al diablo que verlo venir",
    "No es oro todo lo que aparece en Instagram",
    "No hay atajo sin trabajo",
    "No hay dos sin tres",
    "No hay mal que por bien no venga",
    "No hay rosa sin espinas",
    "No por mucho madrugar amanece más temprano",
    "No se ganó Zamora en una hora",
    "No todo el monte es orégano",
    "No vendas la piel del oso antes de cazarlo",
    "Nunca digas de esta agua no beberé",
    "Ojo por ojo, diente por diente",
    "Ojos que no ven, corazón que no siente",
    "Oveja que bala, bocado que pierde",
    "Padres vendedores, hijos gastadores; nietos pordioseros",
    "Perro ladrador, poco mordedor",
    "Poco a poco se anda lejos",
    "Por la boca muere el pez",
    "Quien a buen árbol se arrima, buena sombra le cobija",
    "Quien bien te quiere te hará llorar",
    "Quien calla, otorga",
    "Quien con niños se acuesta, meado se levanta",
    "Quien espera, desespera",
    "Quien mal anda, mal acaba",
    "Quien mucho abarca, poco aprieta",
    "Quien mucho duerme, poco aprende",
    "Quien no arriesga, no gana",
    "Quien no llora, no mama",
    "Quien ríe el último, ríe mejor",
    "Quien siembra vientos, recoge tempestades",
    "Quien tiene boca, se equivoca",
    "Sarna con gusto no pica",
    "Si la montaña no va a Mahoma, Mahoma va a la montaña",
    "Sobre gustos no hay nada escrito",
    "Tanto va el cántaro a la fuente que al final se rompe",
    "Tiran más dos tetas que dos carretas",
    "Todos los caminos llevan a Roma",
    "Un clavo saca otro clavo",
    "Una golondrina no hace verano",
    "Unos nacen con estrella y otros nacen estrellados",
    "Vale más una imagen que mil palabras",
    "Vísteme despacio que tengo prisa",
    "Zapatero, a tus zapatos",
]

FRASES_AMIGOS = [
    "Sé que mi destino está escrito pero no quiero saberlo - Mi abuela",
    "'Llego tarde' - Maru Espasandín (cada vez que quedas con ella)",
    "Pero yo no lo entiendo, igual es que se me está encogiendo el cerebro - Raquel F.S.",
    "Pareces nuevo/a - Iván V.S.",
    "Estaba tendiendo la ropa - Tania Eiros cada vez que hizo el amor",
    "Follo, fumo y como cerdo, soy un partidazo para cualquier musulmán - Cris Flores Senegal 2025",
    "Si vienes te enseño mi pimiento - Iván V.S.",
    "Somos escarabajos peloteros creando montañas de estiércol - Raquel F.S.",
    "Cerra sesión e volve a entrar - Manuel Reyes, filósofo del s.XXI",
    "Hoy vi un video de un trio, de cómo gestionaban sus gastos y se ahorran pasta - Alicia González",
    "Esto es el chiringuito de peine - Raquel F.S.",
    "'¡Furcia!' (mientras aplasta una hormiga) - Loreto M.S.",
    "Al final en este país la opción más realista de tener una vivienda es ser okupa - Lucía Fisio",
    "Pasarlo bien, venga ciao - Carliños",
    "Entra en modo incógnito - Manuel Reyes, filósofo del s.XXI",
    "Me voy para cama porque el karma existe - Jess S.V.",
    "Eso no es una incidencia, eso es una ñapa de mierda -Raquel F.S.",
    "Pero vamos a ver, las mujeres en navidades no trabajan? ni un solo partido de fútbol femenino ¿luego pretenden cobrar como los hombres? - Jess S.V.",
    "Ya llamé Martin a mi sobrino Daniel y Daniel a mi hijo Martín, soy madre nivel ultra - Sara UK",
    "Donde hay pelito no hay delito - Marga G.C.",
    "Eu probaría con espacios - Manuel Reyes, filósofo del s.XXI",
    "Si el césped ha crecido, juguemos el partido - Iván V.S.",
    "Chupame la cruz - María Bipo",
    "Soy la mejor parte de este trío - Lucía M.G.",
    "24 horas parenme pouco - Manuel Reyes, filósofo del s.XXI",
    "Hay varios hombres en esa habitación y sabes ¿por qué no encontraba el abridor? PORQUE LO TENÍAN ALLÍ - Cris Flores (Senegal 2025)",
    "Donde comes no cagues - Raquel F.S.",
    "En mi casa solo follo yo, ya os voy avisando, que os veo venir - Tania Eiros",
    "Esto es como la alfombra roja de Hollywood, todos parecen maravillosos pero luego tienen una vida de mierda - Raquel F.S.",


]
