# Contenido del bot: palabras curiosas, refranes y frases míticas

PALABRAS_CURIOSAS = [
    "Acendrado: Puro, sin mancha ni defecto. (Del latín 'cinis', ceniza - purificado por el fuego)",
    "Ademán: Movimiento o actitud del cuerpo con que se manifiesta disposición o sentimiento. (Del árabe hispánico 'addamán', garantía)",
    "Albricias: Expresión de júbilo o alegría por una buena noticia. (Del árabe 'al-bušrà', la buena nueva)",
    "Alipende: Persona pilla, traviesa o 'de una pieza'. (Del latín 'a pili pendere', no valer un pelo)",
    "Arrebol: Color rojo de las nubes iluminadas por el sol. (Del latín 'rubor', rojez)",
    "Ataraxia: Imperturbabilidad, serenidad. (Del griego 'ataraktos', sin perturbación)",
    "Aurora: Luz sonrosada que precede a la salida del sol. (Del latín 'aurora', diosa del amanecer)",
    "Bálsamo: Consuelo, alivio para las penas del alma. (Del latín 'balsamum', resina aromática curativa)",
    "Balumba: Conjunto desordenado y excesivo de cosas. (Del latín 'volumen', bulto o rollo)",
    "Bonhomía: Afabilidad, sencillez y bondad en el carácter. (Del francés 'bonhomie', buen hombre)",
    "Cáfila: Conjunto numeroso de personas, animales o cosas. (Del árabe 'qáfila', caravana)",
    "Crepúsculo: Claridad entre el día y la noche. (Del latín 'crepusculum', luz incierta)",
    "Denuedo: Brío, esfuerzo, valor, intrepidez. (Del latín 'de-nitidus', sin brillo - esfuerzo por brillar)",
    "Duende: Encanto misterioso e inexplicable. (Del latín 'dominus', dueño de la casa)",
    "Efímero: Que dura muy poco tiempo, pasajero. (Del griego 'ephémeros', de un solo día)",
    "Elocuente: Que se expresa con claridad y convicción. (Del latín 'eloquens', que habla bien)",
    "Embeleco: Engaño con que se pretende alucinar a alguien. (Origen incierto, posiblemente del latín 'imbecillus')",
    "Epifanía: Manifestación repentina de una idea o verdad. (Del griego 'epipháneia', aparición)",
    "Etéreo: Sutil, tan delicado que parece no ser de este mundo. (Del latín 'aether', cielo superior)",
    "Evanescente: Que se desvanece como el vapor. (Del latín 'evanescere', desaparecer)",
    "Fruslería: Cosa de poco valor o importancia. (Del latín 'frustulum', pedacito)",
    "Gazmoño: Que finge devoción o modestia exagerada. (Origen incierto, quizá onomatopéyico)",
    "Hogaño: En este año, en la época actual. (Del latín 'hoc anno', este año)",
    "Ignoto: Desconocido, no descubierto. (Del latín 'ignotus', no conocido)",
    "Indócil: Que no es obediente. (Del latín 'indocilis', difícil de enseñar)",
    "Inefable: Que no se puede explicar con palabras. (Del latín 'ineffabilis', indecible)",
    "Jolgorio: Diversión bulliciosa, fiesta ruidosa. (Del latín 'gaudium', gozo)",
    "Lacónico: Breve, conciso, que usa pocas palabras. (De Laconia, región de Esparta, famosos por su brevedad)",
    "Limerencia: Atracción romántica obsesiva e involuntaria. (Término acuñado en 1979 por Dorothy Tennov)",
    "Medroso: Que tiene miedo con facilidad. (Del latín 'metus', miedo)",
    "Melifluo: Dulce y tierno en el trato o manera de hablar. (Del latín 'mel', miel + 'fluere', fluir)",
    "Mohíno: Triste, melancólico, disgustado. (Del árabe 'muhín', que humilla)",
    "Nefelibata: Persona soñadora que vive en las nubes. (Del griego 'nephéle', nube + 'bates', el que anda)",
    "Nimio: Insignificante, sin importancia. (Del latín 'nimius', excesivo - cambió de significado)",
    "Obnubilar: Ofuscar, nublar la razón. (Del latín 'obnubilare', cubrir con nubes)",
    "Onírico: Relativo a los sueños. (Del griego 'óneiros', sueño)",
    "Orate: Persona que ha perdido el juicio, loco. (Del latín 'orare', rezar - los locos que rezaban)",
    "Pávido: Tímido, medroso, lleno de pavor. (Del latín 'pavidus', temeroso)",
    "Petricor: Olor de la lluvia al caer sobre tierra seca. (Del griego 'petra', piedra + 'ichor', sangre de los dioses)",
    "Procrastinar: Posponer tareas constantemente. (Del latín 'pro', adelante + 'crastinus', de mañana)",
    "Querencia: Tendencia hacia el lugar de origen o preferido. (Del latín 'quaerere', buscar)",
    "Quimera: Ilusión que se cree posible pero no lo es. (Del griego 'khímaira', monstruo mitológico)",
    "Raudo: Rápido, veloz, precipitado. (Del latín 'rapidus', arrebatado)",
    "Resiliencia: Capacidad de adaptarse a situaciones adversas. (Del latín 'resilire', saltar hacia atrás)",
    "Saudade: Nostalgia melancólica por algo ausente. (Del latín 'solitas', soledad - palabra portuguesa)",
    "Sempiterno: Que durará siempre, eterno. (Del latín 'sempiternus', siempre eterno)",
    "Serendipia: Descubrimiento afortunado e inesperado. (De 'Serendip', antiguo nombre de Sri Lanka)",
    "Soliviantar: Inquietar, alterar el ánimo. (Del latín 'sub', debajo + 'levare', levantar)",
    "Sonámbulo: Que camina mientras duerme. (Del latín 'somnus', sueño + 'ambulare', caminar)",
    "Trasegar: Revolver, cambiar de lugar. (Del latín 'trans', a través + 'siticare', colocar)",
    "Ubérrimo: Muy abundante y fértil. (Del latín 'uberrimus', superlativo de 'uber', fértil)",
    "Vesania: Locura, furia, demencia. (Del latín 'vesania', falta de cordura)",
    "Zalamero: Que hace zalamerías, muy cariñoso con intención. (Del árabe 'salám', paz - saludo exagerado)",
]

REFRANES = [
    "A buen entendedor, pocas palabras bastan",
    "A caballo regalado no le mires el dentado",
    "A falta de pan, buenas son tortas",
    "A otro perro con ese hueso",
    "A palabras necias, oídos sordos",
    "A quien madruga, Dios le ayuda",
    "Agua que no has de beber, déjala correr",
    "Al pan, pan y al vino, vino",
    "Año de nieves, año de bienes",
    "Aunque la mona se vista de seda, mona se queda",
    "Barriga llena, corazón contento",
    "Boda y mortaja, del cielo bajan",
    "Cada loco con su tema",
    "Cara bonita, poco dura",
    "Cría cuervos y te sacarán los ojos",
    "Cuando el río suena, agua lleva",
    "Cuando marzo mayea, mayo marcea",
    "De noche todos los gatos son pardos",
    "De tal palo, tal astilla",
    "Del dicho al hecho hay mucho trecho",
    "Desgracia compartida, menos sentida",
    "Dime con quién andas y te diré quién eres",
    "Dime qué posteas y te diré quién eres",
    "Donde las dan, las toman",
    "El hábito no hace al monje",
    "El ojo del amo engorda el caballo",
    "El que guarda, halla",
    "El que mucho abarca, poco aprieta",
    "El que tropieza dos veces con la misma piedra, merece que se le caiga encima",
    "El tiempo todo lo cura",
    "En boca cerrada no entran moscas",
    "En casa del herrero, cuchillo de palo",
    "Entre broma y broma, la verdad se asoma",
    "Gato escaldado del agua fría huye",
    "Genio y figura hasta la sepultura",
    "Golondrina que por San Blas ves, o se helará o hambre tendrá",
    "Hecha la ley, hecha la VPN",
    "Hierba mala nunca muere",
    "Hijo de tigre sale rayado",
    "La avaricia rompe el saco",
    "La cabra siempre tira al monte",
    "La curiosidad mató al gato",
    "La esperanza es lo último que se pierde",
    "La ocasión hace al ladrón",
    "La pereza anda tan despacio que la pobreza la alcanza",
    "Las apariencias engañan",
    "Lo barato sale caro",
    "Lo prometido es deuda",
    "Lo que no mata, engorda",
    "Los trapos sucios se lavan en casa",
    "Mal de muchos, consuelo de tontos",
    "Más sabe el diablo por viejo que por diablo",
    "Más vale maña que fuerza",
    "Más vale pájaro en mano que ciento volando",
    "Más vale prevenir que curar",
    "Más vale solo que mal acompañado",
    "Más vale tarde que nunca",
    "Más vale un backup a tiempo que cien disculpas después",
    "Muerto el perro, se acabó la rabia",
    "Nadie es profeta en su tierra",
    "No dejes para mañana lo que puedas hacer hoy",
    "No es lo mismo llamar al diablo que verlo venir",
    "No es oro todo lo que aparece en Instagram",
    "No hay atajo sin trabajo",
    "No hay dos sin tres",
    "No hay mal que por bien no venga",
    "No hay rosa sin espinas",
    "No por mucho madrugar amanece más temprano",
    "No se ganó Zamora en una hora",
    "No todo el monte es orégano",
    "No vendas la piel del oso antes de cazarlo",
    "Nunca digas de esta agua no beberé",
    "Ojo por ojo, diente por diente",
    "Ojos que no ven, corazón que no siente",
    "Oveja que bala, bocado que pierde",
    "Padres vendedores, hijos gastadores; nietos pordioseros",
    "Perro ladrador, poco mordedor",
    "Poco a poco se anda lejos",
    "Por la boca muere el pez",
    "Quien a buen árbol se arrima, buena sombra le cobija",
    "Quien bien te quiere te hará llorar",
    "Quien calla, otorga",
    "Quien con niños se acuesta, meado se levanta",
    "Quien espera, desespera",
    "Quien mal anda, mal acaba",
    "Quien mucho abarca, poco aprieta",
    "Quien mucho duerme, poco aprende",
    "Quien no arriesga, no gana",
    "Quien no llora, no mama",
    "Quien ríe el último, ríe mejor",
    "Quien siembra vientos, recoge tempestades",
    "Quien tiene boca, se equivoca",
    "Sarna con gusto no pica",
    "Si la montaña no va a Mahoma, Mahoma va a la montaña",
    "Sobre gustos no hay nada escrito",
    "Tanto va el cántaro a la fuente que al final se rompe",
    "Tiran más dos tetas que dos carretas",
    "Todos los caminos llevan a Roma",
    "Un clavo saca otro clavo",
    "Una golondrina no hace verano",
    "Unos nacen con estrella y otros nacen estrellados",
    "Vale más una imagen que mil palabras",
    "Vísteme despacio que tengo prisa",
    "Zapatero, a tus zapatos",
]

FRASES_AMIGOS = [
    "Sé que mi destino está escrito pero no quiero saberlo - Mi abuela",
    "'Llego tarde' - Maru Espasandín (cada vez que quedas con ella)",
    "Pero yo no lo entiendo, igual es que se me está encogiendo el cerebro - Raquel F.S.",
    "Pareces nuevo/a - Iván V.S.",
    "Estaba tendiendo la ropa - Tania Eiros cada vez que hizo el amor",
    "Follo, fumo y como cerdo, soy un partidazo para cualquier musulmán - Cris Flores Senegal 2025",
    "Si vienes te enseño mi pimiento - Iván V.S.",
    "Somos escarabajos peloteros creando montañas de estiércol - Raquel F.S.",
    "Cerra sesión e volve a entrar - Manuel Reyes, filósofo del s.XXI",
    "Hoy vi un video de un trio, de cómo gestionaban sus gastos y se ahorran pasta - Alicia González",
    "Esto es el chiringuito de peine - Raquel F.S.",
    "'¡Furcia!' (mientras aplasta una hormiga) - Loreto M.S.",
    "Al final en este país la opción más realista de tener una vivienda es ser okupa - Lucía Fisio",
    "Pasarlo bien, venga ciao - Carliños",
    "Entra en modo incógnito - Manuel Reyes, filósofo del s.XXI",
    "Me voy para cama porque el karma existe - Jess S.V.",
    "Eso no es una incidencia, eso es una ñapa de mierda -Raquel F.S.",
    "Pero vamos a ver, las mujeres en navidades no trabajan? ni un solo partido de fútbol femenino ¿luego pretenden cobrar como los hombres? - Jess S.V.",
    "Ya llamé Martin a mi sobrino Daniel y Daniel a mi hijo Martín, soy madre nivel ultra - Sara UK",
    "Donde hay pelito no hay delito - Marga G.C.",
    "Eu probaría con espacios - Manuel Reyes, filósofo del s.XXI",
    "Si el césped ha crecido, juguemos el partido - Iván V.S.",
    "Chupame la cruz - María Bipo",
    "Soy la mejor parte de este trío - Lucía M.G.",
    "24 horas parenme pouco - Manuel Reyes, filósofo del s.XXI",
    "Hay varios hombres en esa habitación y sabes ¿por qué no encontraba el abridor? PORQUE LO TENÍAN ALLÍ - Cris Flores (Senegal 2025)",
    "Donde comes no cagues - Raquel F.S.",
    "En mi casa solo follo yo, ya os voy avisando, que os veo venir - Tania Eiros",
    "Esto es como la alfombra roja de Hollywood, todos parecen maravillosos pero luego tienen una vida de mierda - Raquel F.S.",
    "'Estoy de camino Grela ¿qué piso era?' 'El venué fue ayer, Maru' - Maria Espasandín, dios del espacio y el tiempo",


]
