# Contenido del bot: palabras curiosas, refranes y frases míticas

PALABRAS_CURIOSAS = [
    "Acendrado: Puro, sin mancha ni defecto. (Del latín 'cinis', ceniza - purificado por el fuego)",
    "Ademán: Movimiento o actitud del cuerpo con que se manifiesta disposición o sentimiento. (Del árabe hispánico 'addamán', garantía)",
    "Albricias: Expresión de júbilo o alegría por una buena noticia. (Del árabe 'al-bušrà', la buena nueva)",
    "Alipende: Persona pilla, traviesa o 'de una pieza'. (Del latín 'a pili pendere', no valer un pelo)",
    "Arrebol: Color rojo de las nubes iluminadas por el sol. (Del latín 'rubor', rojez)",
    "Ataraxia: Imperturbabilidad, serenidad. (Del griego 'ataraktos', sin perturbación)",
    "Aurora: Luz sonrosada que precede a la salida del sol. (Del latín 'aurora', diosa del amanecer)",
    "Bálsamo: Consuelo, alivio para las penas del alma. (Del latín 'balsamum', resina aromática curativa)",
    "Balumba: Conjunto desordenado y excesivo de cosas. (Del latín 'volumen', bulto o rollo)",
    "Bonhomía: Afabilidad, sencillez y bondad en el carácter. (Del francés 'bonhomie', buen hombre)",
    "Cáfila: Conjunto numeroso de personas, animales o cosas. (Del árabe 'qáfila', caravana)",
    "Crepúsculo: Claridad entre el día y la noche. (Del latín 'crepusculum', luz incierta)",
    "Denuedo: Brío, esfuerzo, valor, intrepidez. (Del latín 'de-nitidus', sin brillo - esfuerzo por brillar)",
    "Duende: Encanto misterioso e inexplicable. (Del latín 'dominus', dueño de la casa)",
    "Efímero: Que dura muy poco tiempo, pasajero. (Del griego 'ephémeros', de un solo día)",
    "Elocuente: Que se expresa con claridad y convicción. (Del latín 'eloquens', que habla bien)",
    "Embeleco: Engaño con que se pretende alucinar a alguien. (Origen incierto, posiblemente del latín 'imbecillus')",
    "Epifanía: Manifestación repentina de una idea o verdad. (Del griego 'epipháneia', aparición)",
    "Etéreo: Sutil, tan delicado que parece no ser de este mundo. (Del latín 'aether', cielo superior)",
    "Evanescente: Que se desvanece como el vapor. (Del latín 'evanescere', desaparecer)",
    "Fruslería: Cosa de poco valor o importancia. (Del latín 'frustulum', pedacito)",
    "Gazmoño: Que finge devoción o modestia exagerada. (Origen incierto, quizá onomatopéyico)",
    "Hogaño: En este año, en la época actual. (Del latín 'hoc anno', este año)",
    "Ignoto: Desconocido, no descubierto. (Del latín 'ignotus', no conocido)",
    "Indócil: Que no es obediente. (Del latín 'indocilis', difícil de enseñar)",
    "Inefable: Que no se puede explicar con palabras. (Del latín 'ineffabilis', indecible)",
    "Jolgorio: Diversión bulliciosa, fiesta ruidosa. (Del latín 'gaudium', gozo)",
    "Lacónico: Breve, conciso, que usa pocas palabras. (De Laconia, región de Esparta, famosos por su brevedad)",
    "Limerencia: Atracción romántica obsesiva e involuntaria. (Término acuñado en 1979 por Dorothy Tennov)",
    "Medroso: Que tiene miedo con facilidad. (Del latín 'metus', miedo)",
    "Melifluo: Dulce y tierno en el trato o manera de hablar. (Del latín 'mel', miel + 'fluere', fluir)",
    "Mohíno: Triste, melancólico, disgustado. (Del árabe 'muhín', que humilla)",
    "Nefelibata: Persona soñadora que vive en las nubes. (Del griego 'nephéle', nube + 'bates', el que anda)",
    "Nimio: Insignificante, sin importancia. (Del latín 'nimius', excesivo - cambió de significado)",
    "Obnubilar: Ofuscar, nublar la razón. (Del latín 'obnubilare', cubrir con nubes)",
    "Onírico: Relativo a los sueños. (Del griego 'óneiros', sueño)",
    "Orate: Persona que ha perdido el juicio, loco. (Del latín 'orare', rezar - los locos que rezaban)",
    "Pávido: Tímido, medroso, lleno de pavor. (Del latín 'pavidus', temeroso)",
    "Petricor: Olor de la lluvia al caer sobre tierra seca. (Del griego 'petra', piedra + 'ichor', sangre de los dioses)",
    "Procrastinar: Posponer tareas constantemente. (Del latín 'pro', adelante + 'crastinus', de mañana)",
    "Querencia: Tendencia hacia el lugar de origen o preferido. (Del latín 'quaerere', buscar)",
    "Quimera: Ilusión que se cree posible pero no lo es. (Del griego 'khímaira', monstruo mitológico)",
    "Raudo: Rápido, veloz, precipitado. (Del latín 'rapidus', arrebatado)",
    "Resiliencia: Capacidad de adaptarse a situaciones adversas. (Del latín 'resilire', saltar hacia atrás)",
    "Saudade: Nostalgia melancólica por algo ausente. (Del latín 'solitas', soledad - palabra portuguesa)",
    "Sempiterno: Que durará siempre, eterno. (Del latín 'sempiternus', siempre eterno)",
    "Serendipia: Descubrimiento afortunado e inesperado. (De 'Serendip', antiguo nombre de Sri Lanka)",
    "Soliviantar: Inquietar, alterar el ánimo. (Del latín 'sub', debajo + 'levare', levantar)",
    "Sonámbulo: Que camina mientras duerme. (Del latín 'somnus', sueño + 'ambulare', caminar)",
    "Trasegar: Revolver, cambiar de lugar. (Del latín 'trans', a través + 'siticare', colocar)",
    "Ubérrimo: Muy abundante y fértil. (Del latín 'uberrimus', superlativo de 'uber', fértil)",
    "Vesania: Locura, furia, demencia. (Del latín 'vesania', falta de cordura)",
    "Zalamero: Que hace zalamerías, muy cariñoso con intención. (Del árabe 'salám', paz - saludo exagerado)",
]

REFRANES = [
    "A buen entendedor, pocas palabras bastan",
    "A caballo regalado no le mires el dentado",
    "A falta de pan, buenas son tortas",
    "A otro perro con ese hueso",
    "A palabras necias, oídos sordos",
    "A quien madruga, Dios le ayuda",
    "Agua que no has de beber, déjala correr",
    "Al pan, pan y al vino, vino",
    "Año de nieves, año de bienes",
    "Aunque la mona se vista de seda, mona se queda",
    "Barriga llena, corazón contento",
    "Boda y mortaja, del cielo bajan",
    "Cada loco con su tema",
    "Cara bonita, poco dura",
    "Cría cuervos y te sacarán los ojos",
    "Cuando el río suena, agua lleva",
    "Cuando marzo mayea, mayo marcea",
    "De noche todos los gatos son pardos",
    "De tal palo, tal astilla",
    "Del dicho al hecho hay mucho trecho",
    "Desgracia compartida, menos sentida",
    "Dime con quién andas y te diré quién eres",
    "Dime qué posteas y te diré quién eres",
    "Donde las dan, las toman",
    "El hábito no hace al monje",
    "El ojo del amo engorda el caballo",
    "El que guarda, halla",
    "El que mucho abarca, poco aprieta",
    "El que tropieza dos veces con la misma piedra, merece que se le caiga encima",
    "El tiempo todo lo cura",
    "En boca cerrada no entran moscas",
    "En casa del herrero, cuchillo de palo",
    "Entre broma y broma, la verdad se asoma",
    "Gato escaldado del agua fría huye",
    "Genio y figura hasta la sepultura",
    "Golondrina que por San Blas ves, o se helará o hambre tendrá",
    "Hecha la ley, hecha la VPN",
    "Hierba mala nunca muere",
    "Hijo de tigre sale rayado",
    "La avaricia rompe el saco",
    "La cabra siempre tira al monte",
    "La curiosidad mató al gato",
    "La esperanza es lo último que se pierde",
    "La ocasión hace al ladrón",
    "La pereza anda tan despacio que la pobreza la alcanza",
    "Las apariencias engañan",
    "Lo barato sale caro",
    "Lo prometido es deuda",
    "Lo que no mata, engorda",
    "Los trapos sucios se lavan en casa",
    "Mal de muchos, consuelo de tontos",
    "Más sabe el diablo por viejo que por diablo",
    "Más vale maña que fuerza",
    "Más vale pájaro en mano que ciento volando",
    "Más vale prevenir que curar",
    "Más vale solo que mal acompañado",
    "Más vale tarde que nunca",
    "Más vale un backup a tiempo que cien disculpas después",
    "Muerto el perro, se acabó la rabia",
    "Nadie es profeta en su tierra",
    "No dejes para mañana lo que puedas hacer hoy",
    "No es lo mismo llamar al diablo que verlo venir",
    "No es oro todo lo que aparece en Instagram",
    "No hay atajo sin trabajo",
    "No hay dos sin tres",
    "No hay mal que por bien no venga",
    "No hay rosa sin espinas",
    "No por mucho madrugar amanece más temprano",
    "No se ganó Zamora en una hora",
    "No todo el monte es orégano",
    "No vendas la piel del oso antes de cazarlo",
    "Nunca digas de esta agua no beberé",
    "Ojo por ojo, diente por diente",
    "Ojos que no ven, corazón que no siente",
    "Oveja que bala, bocado que pierde",
    "Padres vendedores, hijos gastadores; nietos pordioseros",
    "Perro ladrador, poco mordedor",
    "Poco a poco se anda lejos",
    "Por la boca muere el pez",
    "Quien a buen árbol se arrima, buena sombra le cobija",
    "Quien bien te quiere te hará llorar",
    "Quien calla, otorga",
    "Quien con niños se acuesta, meado se levanta",
    "Quien espera, desespera",
    "Quien mal anda, mal acaba",
    "Quien mucho abarca, poco aprieta",
    "Quien mucho duerme, poco aprende",
    "Quien no arriesga, no gana",
    "Quien no llora, no mama",
    "Quien ríe el último, ríe mejor",
    "Quien siembra vientos, recoge tempestades",
    "Quien tiene boca, se equivoca",
    "Sarna con gusto no pica",
    "Si la montaña no va a Mahoma, Mahoma va a la montaña",
    "Sobre gustos no hay nada escrito",
    "Tanto va el cántaro a la fuente que al final se rompe",
    "Tiran más dos tetas que dos carretas",
    "Todos los caminos llevan a Roma",
    "Un clavo saca otro clavo",
    "Una golondrina no hace verano",
    "Unos nacen con estrella y otros nacen estrellados",
    "Vale más una imagen que mil palabras",
    "Vísteme despacio que tengo prisa",
    "Zapatero, a tus zapatos",
]

FRASES_AMIGOS = [
    "Sé que mi destino está escrito pero no quiero saberlo - Mi abuela",
    "'Llego tarde' - Maru Espasandín (cada vez que quedas con ella)",
    "Pero yo no lo entiendo, igual es que se me está encogiendo el cerebro - Raquel F.S.",
    "Pareces nuevo/a - Iván V.S.",
    "Estaba tendiendo la ropa - Tania Eiros cada vez que hizo el amor",
    "Follo, fumo y como cerdo, soy un partidazo para cualquier musulmán - Cris Flores Senegal 2025",
    "Si vienes te enseño mi pimiento - Iván V.S.",
    "Somos escarabajos peloteros creando montañas de estiércol - Raquel F.S.",
    "Cerra sesión e volve a entrar - Manuel Reyes, filósofo del s.XXI",
    "Hoy vi un video de un trio, de cómo gestionaban sus gastos y se ahorran pasta - Alicia González",
    "Esto es el chiringuito de peine - Raquel F.S.",
    "'¡Furcia!' (mientras aplasta una hormiga) - Loreto M.S.",
    "Al final en este país la opción más realista de tener una vivienda es ser okupa - Lucía Fisio",
    "Pasarlo bien, venga ciao - Carliños",
    "Entra en modo incógnito - Manuel Reyes, filósofo del s.XXI",
    "Me voy para cama porque el karma existe - Jess S.V.",
    "Eso no es una incidencia, eso es una ñapa de mierda -Raquel F.S.",
    "Pero vamos a ver, las mujeres en navidades no trabajan? ni un solo partido de fútbol femenino ¿luego pretenden cobrar como los hombres? - Jess S.V.",
    "Ya llamé Martin a mi sobrino Daniel y Daniel a mi hijo Martín, soy madre nivel ultra - Sara UK",
    "Donde hay pelito no hay delito - Marga G.C.",
    "Eu probaría con espacios - Manuel Reyes, filósofo del s.XXI",
    "Si el césped ha crecido, juguemos el partido - Iván V.S.",
    "Chupame la cruz - María Bipo",
    "Soy la mejor parte de este trío - Lucía M.G.",
    "24 horas parenme pouco - Manuel Reyes, filósofo del s.XXI",
    "Hay varios hombres en esa habitación y sabes ¿por qué no encontraba el abridor? PORQUE LO TENÍAN ALLÍ - Cris Flores (Senegal 2025)",
    "Donde comes no cagues - Raquel F.S.",
    "En mi casa solo follo yo, ya os voy avisando, que os veo venir - Tania Eiros",
    "Esto es como la alfombra roja de Hollywood, todos parecen maravillosos pero luego tienen una vida de mierda - Raquel F.S.",
    "'Estoy de camino Grela ¿qué piso era?' 'El venué fue ayer, Maru' - Maria Espasandín, dios del espacio y el tiempo",
]

MITOS_DESMONTADOS = [
    {"mito": "Los humanos solo usamos el 10% del cerebro", "realidad": "Usamos prácticamente todo el cerebro, solo que no todas las áreas a la vez. Las resonancias magnéticas demuestran actividad en todo el cerebro incluso durante el sueño."},
    {"mito": "El pelo y las uñas siguen creciendo después de morir", "realidad": "La piel se deshidrata y se retrae, lo que hace que parezca que han crecido. Pero sin circulación sanguínea, no hay crecimiento celular posible."},
    {"mito": "Los murciélagos son ciegos", "realidad": "Todos los murciélagos pueden ver. Algunos usan la ecolocalización como complemento, pero sus ojos funcionan perfectamente."},
    {"mito": "Napoleón era muy bajito", "realidad": "Medía 1,70m, altura normal para la época. La confusión viene de la diferencia entre pulgadas francesas e inglesas, y la propaganda británica."},
    {"mito": "La Gran Muralla China se ve desde el espacio", "realidad": "No es visible a simple vista desde la órbita terrestre. Es larga pero muy estrecha. Los astronautas lo han desmentido repetidamente."},
    {"mito": "Los toros se enfurecen con el color rojo", "realidad": "Los toros son daltónicos al rojo. Reaccionan al movimiento del capote, no a su color. El rojo es tradición y disimula la sangre."},
    {"mito": "Einstein suspendió matemáticas", "realidad": "Fue un estudiante brillante en matemáticas y física. Este mito surgió de una confusión con el sistema de calificaciones suizo."},
    {"mito": "Los camaleones cambian de color para camuflarse", "realidad": "Cambian de color principalmente para comunicarse y regular su temperatura. El camuflaje es un efecto secundario."},
    {"mito": "Tragamos 8 arañas al año mientras dormimos", "realidad": "Las arañas evitan a los humanos por las vibraciones. Este 'dato' fue inventado en 1993 para demostrar cómo se propagan los bulos."},
    {"mito": "El agua gira en sentido contrario en cada hemisferio", "realidad": "El efecto Coriolis es demasiado débil para afectar al agua de un desagüe. La dirección depende de la forma del lavabo y cómo cae el agua."},
    {"mito": "Los vikingos llevaban cascos con cuernos", "realidad": "No hay evidencia arqueológica de cascos con cuernos. Esta imagen fue popularizada por óperas del siglo XIX."},
    {"mito": "Despertar a un sonámbulo es peligroso", "realidad": "Puede ser confuso y desorientador para ellos, pero no es peligroso. Es más arriesgado dejarlos caminar dormidos."},
    {"mito": "Los perros ven en blanco y negro", "realidad": "Ven en color, aunque con menos variedad que los humanos. Perciben azules y amarillos, pero no distinguen bien rojos y verdes."},
    {"mito": "El alcohol calienta el cuerpo", "realidad": "Dilata los vasos sanguíneos superficiales dando sensación de calor, pero en realidad acelera la pérdida de calor corporal."},
    {"mito": "Las vacunas causan autismo", "realidad": "El estudio que lo afirmaba fue un fraude. Su autor perdió la licencia médica. Décadas de investigación han demostrado que no hay relación."},
    {"mito": "Solo tenemos 5 sentidos", "realidad": "Tenemos al menos 9: vista, oído, gusto, olfato, tacto, equilibrio, temperatura, dolor y propiocepción (posición del cuerpo)."},
    {"mito": "El azúcar causa hiperactividad en niños", "realidad": "Múltiples estudios científicos no han encontrado ninguna relación. Es un sesgo de confirmación de los padres."},
    {"mito": "Los tiburones no tienen cáncer", "realidad": "Sí lo tienen. Este mito fue promovido para vender cartílago de tiburón como 'cura' contra el cáncer."},
    {"mito": "Afeitarse hace que el pelo crezca más grueso", "realidad": "El pelo crece igual. Al cortarlo, la punta queda roma en vez de afilada, lo que da sensación de mayor grosor."},
    {"mito": "Un rayo nunca cae dos veces en el mismo sitio", "realidad": "Los rayos caen frecuentemente en los mismos puntos. El Empire State Building recibe unos 25 impactos al año."},
    {"mito": "Los peces tienen memoria de 3 segundos", "realidad": "Los peces pueden recordar cosas durante meses. Se les ha entrenado para realizar tareas complejas."},
    {"mito": "Hay que esperar 24h para denunciar una desaparición", "realidad": "No existe tal norma. Cuanto antes se denuncie, más probabilidades hay de encontrar a la persona."},
    {"mito": "La sangre desoxigenada es azul", "realidad": "La sangre siempre es roja. Las venas se ven azules por cómo la luz atraviesa la piel, no por el color de la sangre."},
    {"mito": "Los diamantes vienen del carbón comprimido", "realidad": "La mayoría se forman a partir de carbono en el manto terrestre. El carbón está demasiado cerca de la superficie."},
    {"mito": "Cristóbal Colón descubrió que la Tierra era redonda", "realidad": "Los griegos ya lo sabían 2000 años antes. Eratóstenes incluso calculó su circunferencia con bastante precisión."},
    {"mito": "Los lemings se suicidan en masa", "realidad": "Este mito fue creado por un documental de Disney de 1958 donde arrojaron lemings por un acantilado."},
    {"mito": "Newton descubrió la gravedad por una manzana", "realidad": "La historia es apócrifa. Newton desarrolló su teoría durante años de trabajo matemático, no por un golpe de inspiración."},
    {"mito": "El chicle tarda 7 años en digerirse", "realidad": "No se digiere, pero tampoco se queda pegado. Pasa por el sistema digestivo y se expulsa normalmente."},
    {"mito": "Los antibióticos curan resfriados y gripes", "realidad": "Los resfriados y gripes son causados por virus. Los antibióticos solo funcionan contra bacterias."},
    {"mito": "Las zanahorias mejoran la visión nocturna", "realidad": "Propaganda británica de la WWII para ocultar el radar. La vitamina A es necesaria, pero el exceso no mejora la vista."},
    {"mito": "Los avestruces esconden la cabeza bajo tierra", "realidad": "Jamás lo hacen. A veces bajan la cabeza para girar los huevos o comer, lo que desde lejos parece que la entierran."},
    {"mito": "Tocar un pájaro bebé hace que su madre lo abandone", "realidad": "Las aves tienen muy poco sentido del olfato. No abandonan a sus crías por olor humano."},
    {"mito": "Los perros sudan por la lengua", "realidad": "Jadear les ayuda a enfriarse, pero sudan principalmente por las almohadillas de las patas."},
    {"mito": "Puedes ver la Estación Espacial a simple vista", "realidad": "Esto sí es verdad, a diferencia de la Gran Muralla China. La ISS es muy brillante y visible en noches despejadas."},
    {"mito": "Las plantas de interior purifican el aire significativamente", "realidad": "El estudio de la NASA era en cámaras selladas. En una casa normal, necesitarías cientos de plantas para notar diferencia."},
    {"mito": "El café deshidrata", "realidad": "La cafeína es diurético leve, pero el agua del café compensa. Cuenta como hidratación."},
    {"mito": "Los gatos siempre caen de pie", "realidad": "A menudo sí, pero no siempre. Y desde poca altura no les da tiempo a girarse."},
    {"mito": "Leer con poca luz daña la vista", "realidad": "Puede causar fatiga ocular temporal, pero no daño permanente a la visión."},
    {"mito": "El MSG (glutamato monosódico) es malo para la salud", "realidad": "Décadas de estudios no han encontrado efectos negativos en dosis normales. El 'síndrome del restaurante chino' fue un mito."},
    {"mito": "Las personas ciegas tienen oído supersensible", "realidad": "No tienen mejor oído físicamente, pero aprenden a usar mejor la información auditiva."},
    {"mito": "El cerebro izquierdo es lógico y el derecho creativo", "realidad": "Las funciones cerebrales no están tan divididas. Ambos hemisferios trabajan juntos en casi todo."},
    {"mito": "Los elefantes le tienen miedo a los ratones", "realidad": "No es cierto. Los elefantes reaccionan a movimientos rápidos, pero no tienen fobia específica a los ratones."},
    {"mito": "Crujir los nudillos causa artritis", "realidad": "Múltiples estudios han demostrado que no hay relación entre crujirse los nudillos y desarrollar artritis."},
    {"mito": "Cortarse el pelo lo hace crecer más rápido", "realidad": "El pelo crece desde la raíz, no desde la punta. Cortarlo no afecta la velocidad de crecimiento."},
    {"mito": "Los humanos descienden de los chimpancés", "realidad": "Compartimos un ancestro común, pero no descendemos de ellos. Son nuestros primos evolutivos, no ancestros."},
    {"mito": "La regla de los 5 segundos para comida que cae al suelo", "realidad": "Las bacterias se transfieren instantáneamente. El tiempo no importa, importa la superficie."},
    {"mito": "El vidrio es un líquido que fluye muy lento", "realidad": "El vidrio es un sólido amorfo. Las ventanas antiguas son más gruesas abajo porque así se fabricaban."},
    {"mito": "Los diferentes partes de la lengua detectan sabores diferentes", "realidad": "Todas las papilas gustativas detectan todos los sabores. El mapa de la lengua es falso."},
    {"mito": "Esperar 30 minutos después de comer para bañarse", "realidad": "No hay evidencia científica de que nadar después de comer cause calambres mortales."},
    {"mito": "Un año de perro equivale a 7 años humanos", "realidad": "La conversión no es lineal. Los perros maduran más rápido al principio y luego más lento."},
    {"mito": "La leche aumenta la producción de mucosidad", "realidad": "Estudios controlados no han encontrado relación entre consumo de lácteos y mucosidad."},
    {"mito": "Solo usamos una fracción de nuestro potencial cerebral", "realidad": "Similar al mito del 10%. Usamos todo el cerebro, diferentes partes para diferentes funciones."},
    {"mito": "Las ballenas expulsan agua por el espiráculo", "realidad": "Expulsan aire caliente que condensa al contacto con el frío. El agua es solo la que estaba encima."},
    {"mito": "El chocolate causa acné", "realidad": "Estudios no han encontrado relación directa. El acné depende más de hormonas y genética."},
    {"mito": "Los goldfish solo viven unos meses", "realidad": "Con buenos cuidados pueden vivir 10-15 años. El problema es que suelen estar mal cuidados."},
    {"mito": "Napoleón era un tirano megalómano", "realidad": "Introdujo reformas legales progresistas. El Código Napoleónico influyó en legislaciones de todo el mundo."},
    {"mito": "Marie Antoinette dijo 'que coman pasteles'", "realidad": "No hay evidencia de que lo dijera. La frase ya existía antes de que ella naciera."},
    {"mito": "Las pirámides fueron construidas por esclavos", "realidad": "Evidencias arqueológicas muestran que fueron trabajadores pagados y bien alimentados."},
    {"mito": "El esperma más rápido fertiliza el óvulo", "realidad": "El óvulo selecciona activamente al espermatozoide. No es solo una carrera de velocidad."},
    {"mito": "Los pollos pueden vivir sin cabeza", "realidad": "Mike el pollo vivió 18 meses sin cabeza, pero fue un caso extremadamente raro por cómo se cortó."},
    {"mito": "Comemos 8 arañas al año mientras dormimos", "realidad": "Las arañas no tienen ningún motivo para entrar en bocas humanas. Es un bulo inventado."},
    {"mito": "El agua del microondas es peligrosa para las plantas", "realidad": "El agua calentada en microondas es idéntica al agua calentada de cualquier otra forma."},
    {"mito": "Los celulares causan cáncer", "realidad": "No emiten radiación ionizante. Décadas de estudio no han encontrado relación causal."},
    {"mito": "Cleopatra era egipcia", "realidad": "Era de origen macedonio-griego, descendiente de Ptolomeo, general de Alejandro Magno."},
    {"mito": "Las moscas viven solo 24 horas", "realidad": "Las moscas domésticas viven aproximadamente un mes en condiciones normales."},
    {"mito": "El cabello se vuelve gris por el estrés", "realidad": "El estrés puede acelerar el proceso, pero el encanecimiento es principalmente genético."},
    {"mito": "Santa Claus fue inventado por Coca-Cola", "realidad": "San Nicolás ya se representaba con rojo antes. Coca-Cola solo popularizó una imagen existente."},
    {"mito": "Los humanos tienen el cerebro más grande", "realidad": "Ballenas y elefantes tienen cerebros más grandes. Lo relevante es la proporción cerebro-cuerpo."},
    {"mito": "El alcohol mata las neuronas", "realidad": "En consumo moderado no mata neuronas. El daño viene del abuso crónico y la deficiencia de tiamina."},
    {"mito": "Shrek está basado en un luchador real", "realidad": "Maurice Tillet, luchador francés con acromegalia, inspiró el diseño del personaje."},
    {"mito": "El agua caliente congela más rápido que la fría", "realidad": "El efecto Mpemba existe pero solo en condiciones muy específicas, no es una regla general."},
    {"mito": "Un centavo lanzado desde el Empire State puede matar", "realidad": "La resistencia del aire limita su velocidad terminal. Dolería, pero no sería letal."},
    {"mito": "Los delfines son los animales más inteligentes después de humanos", "realidad": "Es difícil comparar inteligencias. Cuervos, pulpos y grandes simios también son muy inteligentes."},
    {"mito": "Las plantas sienten dolor", "realidad": "No tienen sistema nervioso. Responden a estímulos, pero no experimentan dolor como los animales."},
    {"mito": "Los koalas están siempre drogados por eucalipto", "realidad": "El eucalipto no es narcótico. Duermen mucho porque su dieta es muy baja en calorías."},
    {"mito": "Solo el 10% de los icebergs es visible", "realidad": "Depende de la densidad del hielo, pero generalmente es entre 10-20% visible."},
    {"mito": "Las cucarachas sobrevivirían una guerra nuclear", "realidad": "Resisten más radiación que humanos, pero muchos insectos y bacterias les superan."},
    {"mito": "Van Gogh se cortó toda la oreja", "realidad": "Se cortó solo una parte del lóbulo de la oreja izquierda, no la oreja completa."},
    {"mito": "Frankenstein es el nombre del monstruo", "realidad": "Frankenstein es el científico. El monstruo no tiene nombre en la novela original."},
]
