# Diccionario de días internacionales y celebraciones
# Formato: (mes, día): "Celebración"

DIAS_INTERNACIONALES = {
    # ENERO
    (1, 1): "Día de la Paz Mundial 🕊️",
    (1, 4): "Día Mundial del Braille",
    (1, 6): "Día de Reyes 👑",
    (1, 11): "Día Internacional del Gracias",
    (1, 13): "Día Mundial del Rock 🎸",
    (1, 17): "Día de los Niños Inventores",
    (1, 20): "Día del Queso Fundido 🧀",
    (1, 21): "Día Internacional del Abrazo 🤗",
    (1, 24): "Día Internacional de la Educación",
    (1, 26): "Día Mundial de la Educación Ambiental",
    (1, 27): "Día Internacional del Holocausto",
    (1, 28): "Día Europeo de la Protección de Datos",
    (1, 29): "Día Internacional de la Privacidad de Datos",
    (1, 30): "Día de la No Violencia y la Paz (y del Croissant 🥐)",
    (1, 31): "Día Internacional de la Cebra 🦓",
    
    # FEBRERO
    (2, 1): "Día Mundial del Galgo 🐕",
    (2, 2): "Día de la Marmota y Día de los Humedales",
    (2, 3): "Día Internacional del Abogado ⚖️",
    (2, 4): "Día Mundial contra el Cáncer 🎗️",
    (2, 5): "Día de Internet Segura",
    (2, 6): "Día de Tolerancia Cero con la Mutilación Genital Femenina",
    (2, 7): "Día de Enviar una Tarjeta a un Amigo 💌",
    (2, 8): "Día Internacional de la Epilepsia",
    (2, 9): "Día Mundial de la Pizza 🍕",
    (2, 10): "Día de las Legumbres 🫘",
    (2, 11): "Día de la Mujer y la Niña en la Ciencia 👩‍🔬",
    (2, 12): "Día de Darwin 🧬",
    (2, 13): "Día Mundial de la Radio 📻",
    (2, 14): "Día de San Valentín 💘",
    (2, 15): "Día Internacional del Cáncer Infantil",
    (2, 16): "Día del Pistacho 🥜",
    (2, 17): "Día del Gato 🐱",
    (2, 18): "Día Internacional del Síndrome de Asperger",
    (2, 19): "Día del Ejército Mexicano",
    (2, 20): "Día Mundial de la Justicia Social",
    (2, 21): "Día Internacional de la Lengua Materna",
    (2, 22): "Día de la Igualdad Salarial",
    (2, 23): "Día del Rotary",
    (2, 24): "Día de la Bandera de México 🇲🇽",
    (2, 25): "Día del Implante Coclear",
    (2, 26): "Día del Pistacho (EEUU)",
    (2, 27): "Día Mundial del Oso Polar 🐻‍❄️",
    (2, 28): "Día de las Enfermedades Raras",
    (2, 29): "Día del Año Bisiesto 📅",
    
    # MARZO
    (3, 1): "Día de la Cero Discriminación 🌈",
    (3, 3): "Día Mundial de la Vida Silvestre 🦁",
    (3, 4): "Día Mundial de la Obesidad",
    (3, 5): "Día del Reciclaje ♻️",
    (3, 8): "Día Internacional de la Mujer 💜",
    (3, 9): "Día del DJ 🎧",
    (3, 10): "Día de Mario Bros 🍄",
    (3, 14): "Día del Número Pi 🥧",
    (3, 15): "Día Mundial del Consumidor",
    (3, 17): "Día de San Patricio ☘️",
    (3, 19): "Día del Padre (España) 👨",
    (3, 20): "Día Internacional de la Felicidad 😊",
    (3, 21): "Día Mundial de la Poesía 📝",
    (3, 22): "Día Mundial del Agua 💧",
    (3, 23): "Día Meteorológico Mundial 🌦️",
    (3, 24): "Día de la Tuberculosis",
    (3, 25): "Día del Niño por Nacer",
    (3, 26): "Día del Documento Digital",
    (3, 27): "Día Mundial del Teatro 🎭",
    (3, 28): "Día del Diálogo para la Comprensión",
    (3, 30): "Hora del Planeta 🌍",
    (3, 31): "Día de la Visibilidad Trans 🏳️‍⚧️",
    
    # ABRIL
    (4, 1): "Día de las Bromas 🤡",
    (4, 2): "Día de la Concienciación sobre el Autismo 🧩",
    (4, 6): "Día Internacional del Deporte",
    (4, 7): "Día Mundial de la Salud 🏥",
    (4, 8): "Día del Pueblo Gitano",
    (4, 10): "Día de los Hermanos 👫",
    (4, 11): "Día del Parkinson",
    (4, 12): "Día de la Cosmonáutica 🚀",
    (4, 13): "Día del Beso 💋",
    (4, 15): "Día del Arte 🎨",
    (4, 17): "Día del Hemofílico",
    (4, 18): "Día de los Monumentos 🏛️",
    (4, 21): "Día de la Creatividad",
    (4, 22): "Día de la Tierra 🌍",
    (4, 23): "Día del Libro y Sant Jordi 📚🌹",
    (4, 25): "Día del ADN 🧬",
    (4, 26): "Día de la Propiedad Intelectual",
    (4, 27): "Día del Diseño Gráfico 🎨",
    (4, 28): "Día de la Seguridad en el Trabajo",
    (4, 29): "Día del Animal 🐾",
    (4, 30): "Día del Jazz 🎷",
    
    # MAYO
    (5, 1): "Día del Trabajo 👷",
    (5, 2): "Día del Atún 🐟",
    (5, 3): "Día de la Libertad de Prensa 📰",
    (5, 4): "Día de Star Wars ⭐",
    (5, 5): "Cinco de Mayo 🇲🇽",
    (5, 8): "Día de la Cruz Roja ➕",
    (5, 9): "Día de Europa 🇪🇺",
    (5, 10): "Día de la Madre (España) 👩",
    (5, 12): "Día de la Enfermería 👩‍⚕️",
    (5, 15): "Día de la Familia 👨‍👩‍👧",
    (5, 17): "Día del Internet 🌐",
    (5, 18): "Día de los Museos 🖼️",
    (5, 20): "Día de las Abejas 🐝",
    (5, 21): "Día del Té 🍵",
    (5, 22): "Día de la Biodiversidad 🌿",
    (5, 25): "Día del Orgullo Friki 🤓",
    (5, 28): "Día del Hamburguesa 🍔",
    (5, 29): "Día del Pacificador",
    (5, 31): "Día Sin Tabaco 🚭",
    
    # JUNIO
    (6, 1): "Día de la Leche 🥛",
    (6, 3): "Día de la Bicicleta 🚲",
    (6, 5): "Día del Medio Ambiente 🌳",
    (6, 6): "Día del Idioma Ruso",
    (6, 8): "Día de los Océanos 🌊",
    (6, 12): "Día contra el Trabajo Infantil",
    (6, 13): "Día del Escritor",
    (6, 14): "Día del Donante de Sangre 🩸",
    (6, 15): "Día del Viento 💨",
    (6, 17): "Día contra la Desertificación 🏜️",
    (6, 18): "Día del Picnic 🧺",
    (6, 19): "Día del Fútbol ⚽",
    (6, 20): "Día del Refugiado",
    (6, 21): "Día de la Música 🎵 y Solsticio de Verano ☀️",
    (6, 23): "Día de las Viudas",
    (6, 25): "Día del Marino",
    (6, 26): "Día contra las Drogas",
    (6, 27): "Día de las Microempresas",
    (6, 28): "Día del Orgullo LGTBI+ 🏳️‍🌈",
    (6, 30): "Día de las Redes Sociales 📱",
    
    # JULIO
    (7, 1): "Día del Reggae 🇯🇲",
    (7, 2): "Día de los OVNIs 🛸",
    (7, 4): "Día de la Independencia de EEUU 🇺🇸",
    (7, 6): "Día del Beso Robado 💋",
    (7, 7): "Día del Chocolate 🍫",
    (7, 11): "Día de la Población Mundial",
    (7, 13): "Día del Rock 🤘",
    (7, 15): "Día de las Habilidades de los Jóvenes",
    (7, 17): "Día del Emoji 😀",
    (7, 18): "Día de Nelson Mandela",
    (7, 20): "Día del Amigo 🤝",
    (7, 22): "Día del Cerebro 🧠",
    (7, 25): "Día de Santiago Apóstol (España)",
    (7, 26): "Día de los Abuelos 👴👵",
    (7, 28): "Día del Hepatitis",
    (7, 29): "Día del Tigre 🐯",
    (7, 30): "Día de la Amistad",
    (7, 31): "Día del Aguacate 🥑",
    
    # AGOSTO
    (8, 1): "Día de la Alegría 😄",
    (8, 5): "Día de la Cerveza 🍺",
    (8, 8): "Día del Gato 🐱 y del Órgano",
    (8, 9): "Día de los Pueblos Indígenas",
    (8, 10): "Día del Holgazán 😴",
    (8, 12): "Día de la Juventud",
    (8, 13): "Día de los Zurdos ✋",
    (8, 15): "Día de la Asunción",
    (8, 17): "Día del Gato Negro 🐈‍⬛",
    (8, 19): "Día de la Fotografía 📷",
    (8, 20): "Día del Mosquito 🦟",
    (8, 21): "Día del Turista Seniors",
    (8, 23): "Día del Hashtag #️⃣",
    (8, 26): "Día del Perro 🐕",
    (8, 29): "Día del Gamer 🎮",
    (8, 30): "Día de las Víctimas de Desaparición Forzada",
    (8, 31): "Día de la Solidaridad",
    
    # SEPTIEMBRE
    (9, 5): "Día de la Caridad",
    (9, 8): "Día de la Alfabetización 📖",
    (9, 10): "Día de la Prevención del Suicidio",
    (9, 12): "Día de las Naciones Unidas",
    (9, 13): "Día del Programador 💻",
    (9, 15): "Día de la Democracia",
    (9, 16): "Día del Ozono 🌏",
    (9, 17): "Día de la Seguridad del Paciente",
    (9, 19): "Día del Pirata ☠️ ¡Arrr!",
    (9, 21): "Día de la Paz ☮️",
    (9, 22): "Día Sin Coches 🚗❌",
    (9, 23): "Día de las Lenguas de Señas 🤟",
    (9, 26): "Día de los Idiomas 🗣️",
    (9, 27): "Día del Turismo ✈️",
    (9, 28): "Día de la Rabia",
    (9, 29): "Día del Corazón ❤️",
    (9, 30): "Día de la Traducción",
    
    # OCTUBRE
    (10, 1): "Día del Café ☕ y de la Música",
    (10, 2): "Día de la No Violencia",
    (10, 4): "Día del Animal 🐾",
    (10, 5): "Día del Docente 👨‍🏫",
    (10, 7): "Día del Algodón",
    (10, 9): "Día del Correo 📬",
    (10, 10): "Día de la Salud Mental 🧠",
    (10, 11): "Día de la Niña 👧",
    (10, 12): "Día de la Hispanidad 🇪🇸",
    (10, 13): "Día de la Reducción de Desastres",
    (10, 15): "Día del Bastón Blanco 🦯",
    (10, 16): "Día de la Alimentación 🍽️",
    (10, 17): "Día contra la Pobreza",
    (10, 20): "Día de la Estadística 📊",
    (10, 21): "Día del Selfie 🤳",
    (10, 24): "Día de las Naciones Unidas 🇺🇳",
    (10, 25): "Día de la Pasta 🍝",
    (10, 29): "Día del Internet 🌐",
    (10, 31): "Halloween 🎃",
    
    # NOVIEMBRE
    (11, 1): "Día de Todos los Santos",
    (11, 2): "Día de los Difuntos 💀",
    (11, 3): "Día del Sándwich 🥪",
    (11, 8): "Día del Urbanismo 🏙️",
    (11, 9): "Día del Inventor",
    (11, 10): "Día de la Ciencia 🔬",
    (11, 11): "Día del Soltero",
    (11, 13): "Día de la Amabilidad 😊",
    (11, 14): "Día de la Diabetes",
    (11, 16): "Día de la Tolerancia",
    (11, 17): "Día del Estudiante 📚",
    (11, 19): "Día del Hombre 👨",
    (11, 20): "Día de los Derechos del Niño 👶",
    (11, 21): "Día de la Televisión 📺",
    (11, 25): "Día contra la Violencia de Género 💜",
    (11, 26): "Día del Olivo 🫒",
    (11, 29): "Día de la Solidaridad con Palestina",
    (11, 30): "Día de la Seguridad Informática 🔒",
    
    # DICIEMBRE
    (12, 1): "Día del SIDA 🎗️",
    (12, 3): "Día de las Personas con Discapacidad",
    (12, 4): "Día de los Bancos",
    (12, 5): "Día del Voluntario 🤝",
    (12, 6): "Día de la Constitución Española 🇪🇸",
    (12, 7): "Día de la Aviación Civil ✈️",
    (12, 8): "Día de la Inmaculada Concepción",
    (12, 9): "Día contra la Corrupción",
    (12, 10): "Día de los Derechos Humanos",
    (12, 11): "Día de las Montañas ⛰️",
    (12, 12): "Día de la Cobertura Universal de Salud",
    (12, 14): "Día del Mono 🐒",
    (12, 18): "Día de los Migrantes",
    (12, 20): "Día de la Solidaridad Humana",
    (12, 21): "Solsticio de Invierno ❄️",
    (12, 24): "Nochebuena 🎄",
    (12, 25): "Navidad 🎅",
    (12, 28): "Día de los Santos Inocentes 🤪",
    (12, 31): "Nochevieja 🎆",
}
