# Efemérides curadas - Eventos históricos conocidos y curiosos
# Formato: (mes, día): "Año: Evento"

EFEMERIDES = {
    # ENERO
    (1, 1): "1983: Internet nace oficialmente cuando ARPANET adopta el protocolo TCP/IP",
    (1, 4): "2004: El rover Spirit de la NASA aterriza en Marte",
    (1, 6): "1412: Nace Juana de Arco, heroína francesa",
    (1, 7): "2015: Atentado terrorista contra la revista Charlie Hebdo en París",
    (1, 9): "2007: Steve Jobs presenta el primer iPhone",
    (1, 12): "1971: Se estrena 'All in the Family', serie que revolucionó la TV",
    (1, 15): "2001: Se lanza Wikipedia, la enciclopedia libre",
    (1, 17): "1706: Nace Benjamin Franklin, inventor del pararrayos",
    (1, 20): "2009: Barack Obama jura como primer presidente afroamericano de EEUU",
    (1, 24): "1984: Apple lanza el Macintosh, el primer ordenador personal con ratón",
    (1, 27): "1945: El Ejército Rojo libera el campo de Auschwitz",
    (1, 28): "1986: El transbordador Challenger explota 73 segundos después del despegue",
    (1, 30): "1969: Los Beatles dan su último concierto en la azotea de Apple Records",
    (1, 31): "1990: Abre el primer McDonald's en Moscú, con colas de 6 horas",
    
    # FEBRERO
    (2, 1): "2003: El transbordador Columbia se desintegra al reentrar a la atmósfera",
    (2, 2): "1959: Buddy Holly, Ritchie Valens y Big Bopper mueren en un accidente aéreo ('El día que murió la música')",
    (2, 4): "2004: Mark Zuckerberg lanza Facebook desde su habitación en Harvard",
    (2, 6): "1952: Muere el rey Jorge VI; su hija se convierte en Isabel II",
    (2, 7): "1964: Los Beatles llegan a EEUU y comienza la 'Beatlemanía'",
    (2, 8): "1996: Se aprueba en EEUU la Ley de Telecomunicaciones que desregula Internet",
    (2, 11): "1990: Nelson Mandela es liberado tras 27 años en prisión",
    (2, 12): "1809: Nace Charles Darwin, padre de la teoría de la evolución",
    (2, 14): "1876: Alexander Graham Bell patenta el teléfono",
    (2, 15): "2005: Se funda YouTube por tres ex empleados de PayPal",
    (2, 17): "1600: Giordano Bruno es quemado en la hoguera por herejía",
    (2, 18): "1930: Se descubre Plutón (aunque luego lo degradaron a planeta enano)",
    (2, 20): "1962: John Glenn se convierte en el primer estadounidense en orbitar la Tierra",
    (2, 22): "1997: Científicos escoceses anuncian la clonación de la oveja Dolly",
    (2, 24): "1981: El golpe de Estado del 23-F fracasa en España",
    (2, 28): "1953: Watson y Crick descubren la estructura del ADN",
    
    # MARZO
    (3, 1): "1872: Se establece Yellowstone como el primer parque nacional del mundo",
    (3, 4): "1789: Entra en vigor la Constitución de EEUU",
    (3, 6): "1899: Bayer registra la marca 'Aspirina'",
    (3, 8): "1917: Comienza la Revolución Rusa con protestas de mujeres en San Petersburgo",
    (3, 10): "1876: Alexander Graham Bell realiza la primera llamada telefónica: 'Watson, venga aquí'",
    (3, 12): "1989: Tim Berners-Lee propone la World Wide Web",
    (3, 14): "1879: Nace Albert Einstein en Ulm, Alemania",
    (3, 15): "44 a.C.: Julio César es asesinado en el Senado romano ('¡Tú también, Bruto!')",
    (3, 17): "1845: Se patenta la goma elástica",
    (3, 20): "2003: EEUU invade Irak, comienza la Guerra del Golfo",
    (3, 21): "1963: Se cierra la prisión de Alcatraz tras 29 años de funcionamiento",
    (3, 24): "1989: El petrolero Exxon Valdez derrama 41 millones de litros en Alaska",
    (3, 26): "1827: Muere Beethoven durante una tormenta; según la leyenda, alzó el puño hacia el cielo",
    (3, 28): "1979: Accidente nuclear en Three Mile Island, EEUU",
    (3, 30): "1867: EEUU compra Alaska a Rusia por 7,2 millones de dólares",
    
    # ABRIL
    (4, 1): "1976: Steve Jobs y Steve Wozniak fundan Apple en un garaje",
    (4, 2): "2005: Muere el Papa Juan Pablo II",
    (4, 4): "1968: Martin Luther King Jr. es asesinado en Memphis",
    (4, 6): "1896: Se celebran los primeros Juegos Olímpicos modernos en Atenas",
    (4, 9): "1865: El general Lee se rinde, termina la Guerra Civil estadounidense",
    (4, 10): "1912: El Titanic zarpa de Southampton en su viaje inaugural (y último)",
    (4, 12): "1961: Yuri Gagarin se convierte en el primer humano en el espacio",
    (4, 14): "1865: Abraham Lincoln es disparado en el teatro Ford",
    (4, 15): "1912: El Titanic se hunde tras chocar con un iceberg",
    (4, 18): "1955: Muere Albert Einstein en Princeton",
    (4, 20): "1889: Nace Adolf Hitler en Austria",
    (4, 22): "1970: Se celebra el primer Día de la Tierra",
    (4, 23): "1616: Mueren Cervantes y Shakespeare (aunque no el mismo día por el calendario)",
    (4, 25): "1953: Watson y Crick publican la estructura del ADN en Nature",
    (4, 26): "1986: Explosión en la central nuclear de Chernóbil",
    (4, 28): "2001: Dennis Tito se convierte en el primer turista espacial",
    (4, 30): "1945: Adolf Hitler se suicida en su búnker de Berlín",
    
    # MAYO
    (5, 1): "1994: Ayrton Senna muere en el GP de San Marino",
    (5, 2): "2011: Osama bin Laden es abatido por Navy SEALs en Pakistán",
    (5, 4): "1979: Margaret Thatcher se convierte en la primera mujer primer ministro del Reino Unido",
    (5, 5): "1961: Alan Shepard se convierte en el primer estadounidense en el espacio",
    (5, 6): "1994: Se inaugura el Eurotúnel entre Francia e Inglaterra",
    (5, 8): "1945: Día de la Victoria en Europa, fin de la WWII en Europa",
    (5, 10): "1994: Nelson Mandela jura como presidente de Sudáfrica",
    (5, 14): "1796: Edward Jenner administra la primera vacuna (contra la viruela)",
    (5, 15): "1940: Se venden las primeras medias de nylon en EEUU, se agotan en horas",
    (5, 18): "1980: Erupciona el Monte Santa Helena, matando a 57 personas",
    (5, 20): "1927: Charles Lindbergh despega de Nueva York hacia París",
    (5, 21): "1927: Lindbergh aterriza en París, completando el primer vuelo transatlántico en solitario",
    (5, 24): "1844: Samuel Morse envía el primer mensaje telegráfico: '¿Qué ha hecho Dios?'",
    (5, 25): "1977: Se estrena 'Star Wars' y cambia el cine para siempre",
    (5, 28): "1987: Un alemán de 19 años aterriza una avioneta en la Plaza Roja de Moscú",
    (5, 29): "1953: Edmund Hillary y Tenzing Norgay conquistan el Everest",
    
    # JUNIO
    (6, 1): "2009: Air France 447 desaparece sobre el Atlántico",
    (6, 4): "1989: Masacre de Tiananmén en China",
    (6, 5): "1981: Se identifican los primeros casos de SIDA en EEUU",
    (6, 6): "1944: Día D: los Aliados desembarcan en Normandía",
    (6, 8): "1949: Se publica '1984' de George Orwell",
    (6, 11): "1963: Un monje budista se inmola en Saigón en protesta",
    (6, 12): "1987: Reagan pronuncia su famoso discurso '¡Derribe este muro!'",
    (6, 15): "1215: El rey Juan firma la Carta Magna",
    (6, 17): "1972: Cinco hombres son arrestados por allanamiento en el Watergate",
    (6, 18): "1815: Napoleón es derrotado en Waterloo",
    (6, 20): "1975: Se estrena 'Tiburón' y crea el concepto de 'blockbuster veraniego'",
    (6, 21): "1948: Columbia Records presenta el disco LP de vinnil",
    (6, 23): "1868: Se patenta la máquina de escribir",
    (6, 25): "1876: La Batalla de Little Bighorn: Custer pierde ante Sitting Bull",
    (6, 26): "1963: JFK pronuncia 'Ich bin ein Berliner' en Berlín Occidental",
    (6, 28): "1914: El archiduque Francisco Fernando es asesinado, desencadenando la WWI",
    (6, 29): "2007: Apple lanza el primer iPhone al mercado",
    
    # JULIO
    (7, 1): "1979: Sony lanza el Walkman y revoluciona la música portátil",
    (7, 2): "1937: Amelia Earhart desaparece sobre el Pacífico",
    (7, 4): "1776: Se firma la Declaración de Independencia de EEUU",
    (7, 5): "1996: Nace la oveja Dolly, primer mamífero clonado",
    (7, 6): "1885: Louis Pasteur vacuna con éxito contra la rabia",
    (7, 7): "2005: Atentados terroristas en el metro de Londres (7/7)",
    (7, 10): "1962: Se lanza Telstar, el primer satélite de comunicaciones",
    (7, 11): "1979: La estación espacial Skylab se desintegra sobre Australia",
    (7, 14): "1789: Toma de la Bastilla, inicio de la Revolución Francesa",
    (7, 16): "1969: Despega el Apolo 11 hacia la Luna",
    (7, 17): "1955: Abre Disneyland en California",
    (7, 18): "1925: Hitler publica 'Mein Kampf'",
    (7, 20): "1969: Neil Armstrong camina sobre la Luna: 'Un pequeño paso para el hombre...'",
    (7, 21): "1969: Armstrong y Aldrin caminan sobre la Luna por última vez",
    (7, 22): "1934: El FBI mata a John Dillinger, 'Enemigo Público Número 1'",
    (7, 25): "1978: Nace Louise Brown, el primer bebé probeta",
    (7, 27): "1953: Termina la Guerra de Corea (técnicamente, solo un armisticio)",
    (7, 29): "1981: El Príncipe Carlos y Diana Spencer se casan ante 750 millones de espectadores",
    (7, 30): "1966: Inglaterra gana su único Mundial de fútbol en Wembley",
    
    # AGOSTO
    (8, 1): "1981: MTV emite su primer vídeo: 'Video Killed the Radio Star'",
    (8, 2): "1990: Irak invade Kuwait, comienza la Guerra del Golfo",
    (8, 4): "1944: Ana Frank y su familia son descubiertos por los nazis",
    (8, 5): "1962: Marilyn Monroe es encontrada muerta en su casa",
    (8, 6): "1945: EEUU lanza la bomba atómica sobre Hiroshima",
    (8, 8): "1974: Nixon anuncia su dimisión por el escándalo Watergate",
    (8, 9): "1945: EEUU lanza la segunda bomba atómica sobre Nagasaki",
    (8, 12): "1981: IBM lanza el PC, el ordenador personal que cambió el mundo",
    (8, 13): "1961: Comienza la construcción del Muro de Berlín",
    (8, 15): "1969: Comienza el festival de Woodstock",
    (8, 16): "1977: Muere Elvis Presley, el Rey del Rock",
    (8, 17): "1987: Rudolf Hess se suicida en la prisión de Spandau",
    (8, 19): "1991: Golpe de Estado fallido en la URSS acelera su disolución",
    (8, 21): "1959: Hawái se convierte en el estado número 50 de EEUU",
    (8, 23): "1989: Dos millones de personas forman una cadena humana de 600 km en los países bálticos",
    (8, 24): "79: El Vesubio entra en erupción y destruye Pompeya",
    (8, 25): "1991: Linus Torvalds anuncia Linux en un grupo de noticias",
    (8, 28): "1963: Martin Luther King pronuncia 'I Have a Dream'",
    (8, 31): "1997: Diana de Gales muere en un accidente de coche en París",
    
    # SEPTIEMBRE
    (9, 1): "1939: Alemania invade Polonia, comienza la Segunda Guerra Mundial",
    (9, 2): "1945: Japón firma la rendición, fin oficial de la WWII",
    (9, 3): "1967: Suecia cambia al carril derecho (¡todo el país a la vez!)",
    (9, 4): "1998: Larry Page y Sergey Brin fundan Google en un garaje",
    (9, 5): "1972: Terroristas palestinos asesinan a 11 atletas israelíes en Múnich",
    (9, 7): "2005: Egipto celebra sus primeras elecciones presidenciales multipartidistas",
    (9, 9): "1976: Muere Mao Zedong, líder de China durante 27 años",
    (9, 11): "2001: Atentados terroristas contra las Torres Gemelas y el Pentágono",
    (9, 12): "2007: El asteroide 2007 TU24 pasa a solo 540.000 km de la Tierra",
    (9, 14): "1927: La bailarina Isadora Duncan muere estrangulada por su propia bufanda",
    (9, 15): "2008: Quiebra Lehman Brothers, inicio de la crisis financiera mundial",
    (9, 17): "1787: Se firma la Constitución de EEUU en Filadelfia",
    (9, 19): "1985: Un terremoto de 8.1 devastra Ciudad de México",
    (9, 21): "1937: Se publica 'El Hobbit' de J.R.R. Tolkien",
    (9, 22): "1862: Lincoln anuncia la Proclamación de Emancipación",
    (9, 23): "1889: Nintendo se funda en Kioto como empresa de naipes",
    (9, 26): "1969: Los Beatles lanzan 'Abbey Road', su último álbum grabado juntos",
    (9, 28): "1928: Alexander Fleming descubre la penicilina por accidente",
    (9, 30): "1955: James Dean muere en un accidente de coche a los 24 años",
    
    # OCTUBRE
    (10, 1): "1971: Walt Disney World abre sus puertas en Florida",
    (10, 2): "1869: Nace Mahatma Gandhi",
    (10, 3): "1990: Alemania se reunifica oficialmente",
    (10, 4): "1957: La URSS lanza el Sputnik 1, primer satélite artificial",
    (10, 5): "2011: Muere Steve Jobs, cofundador de Apple",
    (10, 6): "1927: Se estrena 'El cantor de jazz', la primera película sonora",
    (10, 9): "1967: El Che Guevara es ejecutado en Bolivia",
    (10, 10): "1985: Muere Orson Welles, director de 'Ciudadano Kane'",
    (10, 12): "1492: Cristóbal Colón llega a América",
    (10, 14): "1947: Chuck Yeager rompe la barrera del sonido",
    (10, 16): "1978: Karol Wojtyła es elegido Papa Juan Pablo II",
    (10, 17): "1989: Un terremoto de 6.9 sacude San Francisco durante un partido de béisbol",
    (10, 19): "1987: Lunes Negro: las bolsas mundiales se desploman un 22%",
    (10, 21): "1879: Edison prueba con éxito la primera bombilla práctica",
    (10, 23): "1956: Comienza la revolución húngara contra la ocupación soviética",
    (10, 25): "1881: Nace Pablo Picasso en Málaga",
    (10, 28): "1886: Se inaugura la Estatua de la Libertad en Nueva York",
    (10, 29): "1929: Martes Negro: se desploma la bolsa, comienza la Gran Depresión",
    (10, 30): "1938: Orson Welles aterroriza EEUU con su emisión de 'La Guerra de los Mundos'",
    
    # NOVIEMBRE
    (11, 1): "1952: EEUU detona la primera bomba de hidrógeno",
    (11, 2): "1947: Primer y único vuelo del Spruce Goose, el avión más grande de su época",
    (11, 3): "1957: La URSS lanza al espacio a Laika, la primera perra astronauta",
    (11, 4): "2008: Barack Obama es elegido presidente de EEUU",
    (11, 9): "1989: Cae el Muro de Berlín",
    (11, 10): "1969: Sesame Street se emite por primera vez",
    (11, 11): "1918: Termina la Primera Guerra Mundial",
    (11, 12): "1927: Se abre el Holland Tunnel, primer túnel bajo el río Hudson",
    (11, 13): "1940: Se estrena 'Fantasía' de Disney",
    (11, 14): "1922: La BBC comienza a emitir",
    (11, 17): "1970: La URSS aterriza el Lunokhod 1, primer rover lunar",
    (11, 19): "1969: Pelé marca su gol número 1.000",
    (11, 20): "1945: Comienzan los Juicios de Núremberg",
    (11, 22): "1963: JFK es asesinado en Dallas",
    (11, 24): "1859: Darwin publica 'El origen de las especies'",
    (11, 25): "1984: Band Aid graba 'Do They Know It's Christmas?'",
    (11, 26): "1922: Howard Carter abre la tumba de Tutankamón",
    (11, 28): "1520: Magallanes cruza el estrecho que llevará su nombre",
    (11, 30): "1872: Se juega el primer partido internacional de fútbol: Escocia 0 - Inglaterra 0",
    
    # DICIEMBRE
    (12, 1): "1955: Rosa Parks se niega a ceder su asiento en el autobús",
    (12, 2): "1942: Enrico Fermi logra la primera reacción nuclear controlada",
    (12, 3): "1992: Se envía el primer SMS de la historia: 'Feliz Navidad'",
    (12, 5): "1933: Se deroga la Ley Seca en EEUU tras 13 años",
    (12, 6): "1865: Se ratifica la 13ª Enmienda: se abole la esclavitud en EEUU",
    (12, 7): "1941: Japón ataca Pearl Harbor, EEUU entra en la WWII",
    (12, 8): "1980: John Lennon es asesinado en Nueva York",
    (12, 10): "1901: Se entregan los primeros Premios Nobel",
    (12, 11): "1972: El Apolo 17 aluniza: última misión tripulada a la Luna",
    (12, 14): "1911: Roald Amundsen llega al Polo Sur",
    (12, 15): "1966: Muere Walt Disney",
    (12, 16): "1773: El Motín del Té en Boston",
    (12, 17): "1903: Los hermanos Wright realizan el primer vuelo motorizado",
    (12, 18): "1958: Se lanza el primer satélite de comunicaciones",
    (12, 20): "1989: EEUU invade Panamá para capturar a Noriega",
    (12, 21): "1937: Se estrena 'Blancanieves', primer largometraje animado de Disney",
    (12, 23): "1888: Van Gogh se corta la oreja tras una pelea con Gauguin",
    (12, 25): "1991: Gorbachov dimite, la URSS deja de existir oficialmente",
    (12, 26): "2004: Un tsunami en el Índico mata a más de 230.000 personas",
    (12, 27): "1932: Se inaugura Radio City Music Hall en Nueva York",
    (12, 28): "1895: Los hermanos Lumière proyectan la primera película en París",
    (12, 31): "1999: Pánico mundial por el 'efecto Y2K' (que no fue para tanto)",
}
